<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE CATALOG[
  <!ELEMENT CATALOG (CD*)>
  <!ELEMENT CD (TITLE,ARTIST,COUNTRY,COMPANY,PRICE,YEAR)>
  <!ELEMENT TITLE (#PCDATA)>
  <!ELEMENT ARTIST (#PCDATA)>
  <!ELEMENT COUNTRY (#PCDATA)>
  <!ELEMENT PRICE (#PCDATA)>
  <!ELEMENT YEAR (#PCDATA)>  
]>
<CATALOG>
  <CD>
    <TITLE>Empire Burlesque</TITLE>
    <ARTIST>Bob Dylan</ARTIST>
    <COUNTRY>USA</COUNTRY>
    <COMPANY>Columbia</COMPANY>
    <PRICE>10.90</PRICE>
    <YEAR>1985</YEAR>
  </CD>
  <CD>
    <TITLE>Hide your heart</TITLE>
    <ARTIST>Bonnie Tyler</ARTIST>
    <COUNTRY>UK</COUNTRY>
    <COMPANY>CBS Records</COMPANY>
    <PRICE>9.90</PRICE>
    <YEAR>1988</YEAR>
  </CD>
  <CD>
    <TITLE>Greatest Hits</TITLE>
    <ARTIST>Dolly Parton</ARTIST>
    <COUNTRY>USA</COUNTRY>
    <COMPANY>RCA</COMPANY>
    <PRICE>9.90</PRICE>
    <YEAR>1982</YEAR>
  </CD>
  <CD>
    <TITLE>Still got the blues</TITLE>
    <ARTIST>Gary Moore</ARTIST>
    <COUNTRY>UK</COUNTRY>
    <COMPANY>Virgin records</COMPANY>
    <PRICE>10.20</PRICE>
    <YEAR>1990</YEAR>
  </CD>
